language: java
jdk: oraclejdk8

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_script:
  - mysql -e 'create database school;'
