language: java
jdk: oraclejdk8

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required
before_install:
  - mysql -u root -e "CREATE DATABASE school"
  - mysql -u root -e "CREATE USER 'travis'@'%' IDENTIFIED BY 'travis'"
  - mysql -u root -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"