language: java
jdk: oraclejdk8

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -u root -e 'CREATE DATABASE school;'
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL ON school.* TO 'admin'@'localhost';"
