services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  mailcatcher:
    restart: on-failure
    image: haravich/fake-smtp-server
    ports:
      - "1080:1080"
      - "1025:1025"